Add page with test filtered by status (pending, unplayed) Review
voyages-sncf-technologies/zucchini-ui pull request #13
Opened 2019-10-03 15:36 UTC by tployon

Review : Add page with test filtered by status (pending, unplayed) 
Regroup both pending filtering feature and unplayed filtering feature.

2019-10-15 12:47 UTC, brossardd commented on zucchini-ui-backend/src/main/java/io/zucchiniui/backend/scenario/domain/ScenarioStatus.java
>      private String status;
Pas très fan du nommage de la méthode et de l'attribut status.

2019-10-15 13:43 UTC, brossardd commented on zucchini-ui-frontend/src/testRunFiltered/components/PendingPageContainer.js
> +import { connect } from "react-redux";
Pourquoi le fichier est nommé PendingPageContainer et non PendingScenariiPageContainer

2019-10-15 13:44 UTC, brossardd commented on zucchini-ui-frontend/src/testRunFiltered/components/UnplayedPageContainer.js
> +import { connect } from "react-redux";
Pourquoi pas renommer UnplayedPageContainer en UnplayedScenariiPageContainer ?

2019-10-15 14:22 UTC, brossardd commented on zucchini-ui-frontend/src/testRunFiltered/components/common/containerUtils.js
> +import { createSelector, createStructuredSelector } from "reselect";
Ce code doit pouvoir être simplifié en :
```suggestion
import { createStructuredSelector } from "reselect";

const selectTestRunId = (state, ownProps) => ownProps.match.params.testRunId;
const selectTestRun = state => state.testRun.testRun;
const selectStats = state => state.testRun.stats;

export function createTestRunFilterPageSelector(title) {
  return createStructuredSelector({
    title: () => title,
    testRunId: selectTestRunId,
    testRun: selectTestRun,
    stats: selectStats
  });
}
```

2019-10-15 14:24 UTC, brossardd commented on zucchini-ui-frontend/src/testRunFiltered/components/common/containerUtils.js
> +}
Ce code doit pouvoir être simplifié en :
```suggestion
import { createStructuredSelector } from "reselect";

const selectTestRunId = (state, ownProps) => ownProps.match.params.testRunId;
const selectTestRun = state => state.testRun.testRun;
const selectStats = state => state.testRun.stats;

export function createTestRunFilterPageSelector(title) {
  return createStructuredSelector({
    title: () => title,
    testRunId: selectTestRunId,
    testRun: selectTestRun,
    stats: selectStats
  });
}
```

2019-10-15 14:42 UTC, brossardd commented on zucchini-ui-frontend/src/testRunFiltered/components/common/TestRunFilteredTableContainer.js
> +  state => state.testRunFiltered.testRunFiltered,
Peut-on renommer testRunFiltered en filteredScenarii ici aussi ?

Le code pourrait ressembler à ça :
`import { connect } from "react-redux";
import { createStructuredSelector } from "reselect";

import ScenarioTable from "../../../ui/components/ScenarioTable";

const selectFilteredScenarii = state => state.filteredScenarii.filteredScenarii;

const selectProps = createStructuredSelector({
  scenarii: selectFilteredScenarii
});

const TestRunFilteredTableContainer = connect(selectProps)(ScenarioTable);

export default TestRunFilteredTableContainer;
`

2019-10-15 14:44 UTC, brossardd commented on zucchini-ui-frontend/src/testRunFiltered/components/common/TestRunFilteredTableContainer.js
> +export default TestRunFilteredTableContainer;
Peut-on renommer testRunFiltered en filteredScenarii ici aussi ?

Le code pourrait ressembler à ça :
`import { connect } from "react-redux";
import { createStructuredSelector } from "reselect";

import ScenarioTable from "../../../ui/components/ScenarioTable";

const selectFilteredScenarii = state => state.filteredScenarii.filteredScenarii;

const selectProps = createStructuredSelector({
  scenarii: selectFilteredScenarii
});

const TestRunFilteredTableContainer = connect(selectProps)(ScenarioTable);

export default TestRunFilteredTableContainer;
`

2019-10-15 14:47 UTC, brossardd requested changes
Quelques simplifications possibles et un peu de renommage.

2019-10-16 07:29 UTC, tployon commented on zucchini-ui-frontend/src/testRunFiltered/components/common/containerUtils.js
> +}
Done

2019-10-16 07:54 UTC, tployon commented on zucchini-ui-frontend/src/testRunFiltered/components/common/TestRunFilteredTableContainer.js
> +export default TestRunFilteredTableContainer;
Simplification OK

2019-10-16 08:00 UTC, tployon commented on zucchini-ui-frontend/src/testRunFiltered/components/PendingPageContainer.js
> +import { connect } from "react-redux";
Le renommage sera à prendre en compte dans une prochaine PR.

2019-10-16 08:21 UTC, tployon commented on zucchini-ui-backend/src/main/java/io/zucchiniui/backend/scenario/domain/ScenarioStatus.java
>      private String status;
A améliorer dans une autre pull request.

2019-10-24 14:14 UTC, merged